name: Prepare Document Translations

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install illuminated
        run: |
          git clone https://github.com/getlantern/illuminated.git
          cd illuminated/cmd
          go build -o ../../ill-bin
          cd ../..
          rm -rf illuminated

      - name: Prepare
        run: |
          ./ill-bin prepare \
            --directory docs \
            --source https://github.com/getlantern/guide.wiki.git

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prepare translations"
          file_pattern: docs/
          branch: "${{ github.ref_name }}"
